/*
 * vFk.java
 *
 * Created on 11 de junio de 2008, 03:47 PM
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import util.Util;

/**
 *
 *
 */
public class vAs extends javax.swing.JDialog {

    ListSelectionModel listSelectionModel = new DefaultListSelectionModel();

    ArrayList<Object> objetos = new ArrayList<>();
    Util util = new Util();
    ArrayList<Object> objetosSeleccionados = new ArrayList<>();
    
    ArrayList<Object> listaObjetos = new ArrayList<>();
    

    private boolean enviar = false;

    /**
     * Creates new form vFk
     *
     * @param parent
     * @param nomArchivo
     * @param titulo
     * @param seleccionMultiple
     * @param listaObjetos
     */
    public vAs(java.awt.Frame parent, String nomArchivo, String titulo, boolean seleccionMultiple, ArrayList<Object> listaObjetos) {
        super(parent, true);
        initComponents();
        this.listaObjetos = listaObjetos;
        if (!seleccionMultiple) {
            txListado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        } else {
            txListado.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        }
        setListadoObjetos(nomArchivo, titulo);
        setObjetosSeleccionados();
    }

    private void setListadoObjetos(String nomArchivo, String titulo) {
        lbTitulo.setText(titulo);
        if (util.desSerializar(nomArchivo) != null) {
            objetos = (ArrayList) util.desSerializar(nomArchivo);
            String[] t = {titulo};
            this.txListado.setModel(new DefaultTableModel(util.setJTable(objetos), t));
        }
        
    }

    
    private void setObjetosSeleccionados(){
        for (int i = 0; i < objetos.size(); i++) {
            for (int j = 0; j < listaObjetos.size(); j++) {
                if (objetos.get(i).toString().equals(listaObjetos.get(j).toString())) {
                    listSelectionModel.addSelectionInterval(i, i);
                }
            }
        }
        this.txListado.setSelectionModel(listSelectionModel);
    }
    public ArrayList<Object> getObjetosSeleccionados() throws Exception {
        int[] numSeleccionados = txListado.getSelectedRows();
        for (int i = 0; i < numSeleccionados.length; i++) {
            objetosSeleccionados.add(txListado.getValueAt(numSeleccionados[i], 0));
        }
        return objetosSeleccionados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lbTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txListado = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitulo.setText("jLabel1");

        txListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        txListado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        txListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txListado);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Seleccionados");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txListadoMouseClicked
    }//GEN-LAST:event_txListadoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        enviar = true;
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enviar = false;
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.txListado.clearSelection();
        setObjetosSeleccionados();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*vFk dialog = new vFk(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                 * */
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable txListado;
    // End of variables declaration//GEN-END:variables

    public boolean isEnviar() {
        return enviar;
    }

    public void setEnviar(boolean enviar) {
        this.enviar = enviar;
    }

}
